import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
data = pd.read_csv('C:/Users/DELL/OneDrive/Documents/fat.csv')
mean_age = data['Age'].mean()
median_age = data['Age'].median()
std_dev_age = data['Age'].std()
mean_fat = data['%Fat'].mean()
median_fat = data['%Fat'].median()
std_dev_fat = data['%Fat'].std()
print("Age statistics:")
print(f"Mean: {mean_age}")
print(f"Median: {median_age}")
print(f"Standard Deviation: {std_dev_age}")
print("\n%Fat statistics:")
print(f"Mean: {mean_fat}")
print(f"Median: {median_fat}")
print(f"Standard Deviation: {std_dev_fat}")
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.boxplot(y=data['Age'])
plt.title("Box Plot of Age")
plt.subplot(1, 2, 2)
sns.boxplot(y=data['%Fat'])
plt.title("Box Plot of %Fat")
plt.tight_layout()
plt.show()
plt.figure(figsize=(8, 6))
plt.scatter(data['Age'], data['%Fat'])
plt.xlabel("Age")
plt.ylabel("%Fat")
plt.title("Scatter Plot of Age vs. %Fat")
plt.grid(True)
plt.show()
plt.figure(figsize=(8, 6))
stats.probplot(data['Age'], dist="norm", plot=plt)
plt.title("Q-Q Plot of Age")
plt.show()
plt.figure(figsize=(8, 6))
stats.probplot(data['%Fat'], dist="norm", plot=plt)
plt.title("Q-Q Plot of %Fat")
plt.show()
